config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  get 'home/index'
  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'
  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true
  validates_length_of :title, minimum: 1, maximum: 140, allow_blank: false
  validates_length_of :text, minimum: 1, maximum: 4000, allow_blank: false
  has_many :comments

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates_length_of :body, minimum: 1, maximum: 4000, allow_blank: false
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]


  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params) 
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to articles_path
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
    
  end 

    private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.author = current_user.username
    @comment.save

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
    
  end 

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :test %><br />
		<%= f.text_area :text %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>

<h3><%= article.title %></h3>

<p>
	<%= article.text %>

<br />
<br />
<i>Create <%= article.author %> at <%= article.created_at %></i>
<hr/>
</p>

<p>
	<%= link_to 'Show', article_path(article) %>
	<% if user_signed_in? %>
		<% if article.author == current_user.username %>|
			<%= link_to 'Edit', edit_article_path(article) %> |
			<%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	<% end %>
</p>

<hr />

<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title, class: "form-control", placeholder: "Text input", style: "width: 400px" %>
	</p>

	<p>
		<%= f.label :text %><br />
		<%= f.text_area :text, class: "form-control", rows: "6", style: "width: 400px" %>
	</p>

	<p>
		<%= f.submit"Save Article", class: "btn btn-success"  %>
	</p>


<% end %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p>
	<%= @article.text %>
	<br />
	<br />
	<i>Create <%= @article.author %> at <%= @article.created_at %></i>
	<hr/>
</p>

<h4>Comments</h4>

<% @article.comments.each do |comment| %>

	<p>
		<%= comment.body %>
		<br />
		<br />
		<i>Said <%= comment.author %> at <%= comment.created_at %></i>
		<hr/>
	</p>

<% end %>

<% if user_signed_in? %>
	<h4>Add comment</h4>

	<p>
		<%= form_for([@article, @article.comments.build]) do |f| %>

			<p>
				<%= f.text_area :body, class: "form-control", rows: "4", style: "width: 300px" %>
			</p>

			<p>
				<%= f.submit"Add", class: "btn btn-success" %>
			</p>
		<% end %>
	</p>

<% else %>
	<i>Please <%= link_to "sign in", new_user_session_path %> or <%= link_to "register", new_user_registration_path %> to leave comments.</i>
<% end %>
<hr/>

app/views/contacts/create.html.erb
<h1>Thanks!</h1>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>
<%= form_for :contact, url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
		<% @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</p>
	<% end %>
	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :message %><br />
		<%= f.text_area :message %>
	</p>
	<p>
		<%= f.submit 'Send message'%>
	</p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <script src="/assets/application.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script data-require="jquery@*" data-semver="3.2.1" src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"></script>
    <link data-require="bootstrap@*" data-semver="3.2.0" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.css" />
    <script data-require="bootstrap@*" data-semver="3.2.0" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>      
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default" role="navigation">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to "Blog & RoR", home_index_path, class: "navbar-brand" %>
              <% if user_signed_in? %>
                <% welcome_username = 'Hi, ' + current_user.username + '!' %>
                <div class="visible-xs-block" style="margin: 15px 75px" align="right">
                  <%= welcome_username %>
                </div>
              <% end %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><%= link_to "Articles", articles_path, class: "active" %></li>
                <li><%= link_to "New", new_article_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <% unless user_signed_in? %>
                  <li><%= link_to "Sign In", new_user_session_path %></li>
                  <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <% else %>
                  <li><div class="hidden-xs" style="margin-top: 15px"><%= welcome_username %></div></li>
                  <li><%= link_to "Sing Out", destroy_user_session_path, method: :delete %></li>
                <% end %>
              </ul>
            </div><!-- /.navbar-collapse -->
      </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About as</h1>

app/views/pages/terms.html.erb
<h1>Terms of service</h1>
<p>
	,mlkaslklLKJlk,msl  ;kljlkjLkj
	aasd
</p>